source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PineKit_Example' do
  pod 'PineKit', :path => '../'
end

target 'PineKit_Tests' do
  pod 'PineKit', :path => '../'  
end

pod 'SnapKit', '~> 0.22.0'
pod 'DLRadioButton', '~> 1.4'
pod 'SwiftyJSON', '~> 2.3.3'
pod 'Alamofire', '~> 3.3'
