source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PineKit_Example', :exclusive => true do
  pod 'PineKit', :path => '../'
end

target 'PineKit_Tests', :exclusive => true do
  pod 'PineKit', :path => '../'

  
end


pod 'Cartography'
pod 'SnapKit', '~> 0.15.0'